const actionTypes = {
  LOAD_PRODUCTS: "ECOMM/LOAD_PRODUCTS",
  SET_SELECTED_PRODUCT:"ECOMM/SET_SELECTED_PRODUCT",
  SET_LOADING:"ECOMM/SET_LOADING",
  SET_ERROR:"ECOMM/SET_ERROR"
};

export { actionTypes };
